apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: project
spec:
  type: ClusterIP
  selector:
    app: todoapp
  ports:
    - port: 7892
      protocol: TCP
      targetPort: 3011