apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: volume-claim
      containers:
        - name: fetchapp
          image: misetius/fetchapp:2.2
          imagePullPolicy: Always
          env:
          - name: PORT
            value: "3010"
          volumeMounts:
          - name: shared-image
            mountPath: /usr/src/app/images
        - name: backend
          image: misetius/backend:2.2
          imagePullPolicy: Always
          env:
          - name: PORT
            value: "3011"        
  




#https://raw.githubusercontent.com/misetius/kubernetesSubmissions/main/the_project/manifests/deployment.yaml