apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: todoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      volumes:
        - name: shared-image
          persistentVolumeClaim:
            claimName: volume-claim
        - name: postgres-information
          configMap:
            name: postgres-configmap
      containers:
        - name: fetchapp
          image: misetius/fetchapp:3.5
          imagePullPolicy: Always
          env:
          - name: PORT
            value: "3010"
          - name: BACKEND_SERVICE
            value: "http://backend-svc:7892/todos"
          - name: BACKEND_URL
            value: "http://34.88.19.24:7892/todos"
          volumeMounts:
          - name: shared-image
            mountPath: /usr/src/app/images
        - name: backend
          image: misetius/backend:3.5
          imagePullPolicy: Always
          env:
          - name: PORT
            value: "3011"   
          - name: HOST
            valueFrom:
              configMapKeyRef:
                name: postgres-configmap
                key: HOST
          - name: PASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres-configmap
                key: PASSWORD
          - name: USER
            valueFrom:
              configMapKeyRef:
                name: postgres-configmap
                key: USER
          - name: DATABASE
            valueFrom:
              configMapKeyRef:
                name: postgres-configmap
                key: DATABASE     
  




#https://raw.githubusercontent.com/misetius/kubernetesSubmissions/main/the_project/manifests/deployment.yaml