apiVersion: v1
kind: Service
metadata:
  name: todoapp-svc
  namespace: project
spec:
  type: LoadBalancer
  selector:
    app: todoapp
  ports:
    - port: 3456
      protocol: TCP
      targetPort: 3001