apiVersion: v1
kind: Service
metadata:
  name: pingpong-svc
  namespace: exercises
spec:
  type: LoadBalancer 
  selector:
    app: pingpong
  ports:
    - port: 4567
      protocol: TCP
      targetPort: 3006