apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/configmap.yaml
  - manifests/deployment.yaml
  - manifests/ingress.yaml
  - manifests/service.yaml
  - manifests/service2.yaml
  - manifests/backendService.yaml
  - manifests/statefulset.yaml
  - manifests/CronJob.yaml

images:
- name: project/image
  newName: misetius/fetchapp:3.5

- name: project2/image2
  newName: misetius/backend:3.5

