apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/configmap.yaml
- manifests/ingress.yaml
- manifests/service.yaml
- manifests/service2.yaml
- manifests/backendService.yaml
- manifests/statefulset.yaml
- manifests/deployment.yaml
- manifests/CronJob.yaml


images:
- name: project/image
  newName: misetius/fetchapp
  newTag: ec8762718d7194a9f11210da0b299f274a70ea72
- name: project2/image2
  newName: misetius/backend
  newTag: ec8762718d7194a9f11210da0b299f274a70ea72
