apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      volumes:
        - name: shared-file
          emptyDir: {}
        - name: shared-pong
          persistentVolumeClaim:
            claimName: volume-claim
      containers:
        - name: getlogoutput
          image: misetius/getlog:1.11
          imagePullPolicy: Always
          env:
          - name: PORT
            value: "3005"
          volumeMounts:
          - name: shared-file
            mountPath: /usr/src/app/files 
          - name: shared-pong
            mountPath: /usr/src/app/pongs
        - name: loggenerator
          image: misetius/generatelog:1.11
          imagePullPolicy: Always
          env:
          - name: PORT
            value: "3007"
          volumeMounts:
          - name: shared-file
            mountPath: /usr/src/app/files 


#https://raw.githubusercontent.com/misetius/kubernetesSubmissions/main/log_output/manifests/deployment.yaml