apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      volumes:
        - name: shared-file
          emptyDir: {}
#        - name: shared-pong
#          persistentVolumeClaim:
#            claimName: volume-claim
        - name: information
          configMap:
            name: example-configmap
      containers:
        - name: getlogoutput
          image: PROJECT/IMAGE
          imagePullPolicy: Always
          env:
          - name: PORT
            value: "3005"
          - name: MESSAGE
            valueFrom:
              configMapKeyRef:
                name: example-configmap
                key: MESSAGE
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 120
            httpGet:
              path: /
              port: 3005

          volumeMounts:
          - name: shared-file
            mountPath: /usr/src/app/files 
#          - name: shared-pong
#            mountPath: /usr/src/app/pongs
          - name: information
            mountPath: /usr/src/app/information
        - name: loggenerator
          image: PROJECT2/IMAGE2
          imagePullPolicy: Always
          env:
          - name: PORT
            value: "3007"
          volumeMounts:
          - name: shared-file
            mountPath: /usr/src/app/files 


#https://raw.githubusercontent.com/misetius/kubernetesSubmissions/main/log_output/manifests/deployment.yaml