apiVersion: v1
kind: Service
metadata:
  namespace: exercises
  name: logoutput-svc
spec:
  type: LoadBalancer
  selector:
    app: logoutput
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3005