apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/configmap.yaml
- manifests/deployment.yaml
- manifests/service.yaml


images:
- name: project/image
  newName: misetius/getlog
  newTag: 61ff7716a88aeec26e44b58e0ef1c240837b1cd6
- name: project2/image2
  newName: misetius/generatelog
  newTag: 61ff7716a88aeec26e44b58e0ef1c240837b1cd6
