apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manifests/configmap.yaml
- manifests/deployment.yaml
- manifests/service.yaml


images:
- name: project/image
  newName: misetius/getlog
  newTag: 69ec18c9f3f98c7fdc2010c39a975bf7f901e125
- name: project2/image2
  newName: misetius/generatelog
  newTag: 69ec18c9f3f98c7fdc2010c39a975bf7f901e125
