name: Build and publish project application

on:
  push:

jobs:
  build-publish-project:
    name: Build, Push, Release Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

        


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # tag image with the GitHub SHA to get a unique tag
      - name: Build and publish get log
        run: |-
          docker build --tag "misetius/fetchapp:$GITHUB_SHA" the_project
          docker push "misetius/fetchapp:$GITHUB_SHA"

      - name: Build and publish get log
        run: |-
          docker build --tag "misetius/backend:$GITHUB_SHA" the_project/backend
          docker push "misetius/backend:$GITHUB_SHA"

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Use right image
        run: cd the_project && kustomize edit set image project/image=misetius/fetchapp:$GITHUB_SHA 
      - name: Use right image
        run: cd the_project && kustomize edit set image project2/image2=misetius/backend:$GITHUB_SHA 

      - name: commit kustomization.yaml to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: 'kustomization.yaml'
          message: New version released ${{ github.sha }}
          cwd: './the_project'